version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: .docker/start.dev.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3001:3000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    labels:
      filebeat_collector: true

  elasticsearch:
    image: elasticsearch:7.17.7
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.17.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
