version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: .docker/start.dev.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3001:3000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    labels:
      filebeat_collector: true
